FROM node:20 as builder

WORKDIR /app

COPY package.json ./
RUN npm install --force
RUN npm i -g @ionic/cli

COPY . .

RUN npm run build


FROM nginx:alpine

COPY --from=builder /app/www /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/ /etc/nginx/conf.d/

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
